permalink: /:categories/:year/:month/:title

pygments: true

markdown: rdiscount
rdiscount:
  extensions:
    - smart
    - generate_toc

chapters:
  - Introduction: introduction
  - Getting Started: getting-started
  - Integers and Floating-Point Numbers: integers-and-floating-point-numbers
  - Mathematical Operations: mathematical-operations
  - Complex and Rational Numbers: complex-and-rational-numbers
  - Strings: strings
  - Functions: functions
  - Control Flow: control-flow
  - Variables and Scoping: variables-and-scoping
  - Types: types
  - Methods: methods
  - Constructors: constructors
  - Conversion and Promotion: conversion-and-promotion
  - Arrays: arrays
  - Running External Programs: running-external-programs
  - Metaprogramming: metaprogramming
  - Parallel Computing: parallel-computing
  - Calling C and Fortran Code: calling-c-and-fortran-code
  - Standard Library Reference: standard-library-reference
  - Potential Features: potential-features
  - Performance Tips: performance-tips
