google_analytics: UA-28835595-1
permalink: /:categories/:year/:month/:title
highlighter: rouge
plugins:
  - jekyll-redirect-from
  - jekyll-feed
navigation:
  - title: home
    url: /
  - title: source
    url: "https://github.com/JuliaLang/julia"
  - url: "/downloads/"
    title: downloads
  - url: "https://docs.julialang.org/"
    title: docs
  - url: "/blog/"
    title: blog
  - url: "/community/"
    title: community
  - url: "/ecosystems"
    title: ecosystems
  - url: "/learning/"
    title: learning
  - url: "/teaching/"
    title: teaching
  - url: "/research/"
    title: research
  - url: "/soc/ideas-page.html"
    title: GSoC
  - url: "https://juliacon.org"
    title: juliacon
collections:
  publications:
    permalink: /publications/:path
