permalink: /:categories/:year/:month/:title
highlighter: rouge
gems:
  - jekyll-redirect-from
navigation:
  - title: home
    url: /
  - title: source
    url: "https://github.com/JuliaLang/julia"
  - url: "/downloads/"
    title: downloads
  - url: "http://docs.julialang.org/"
    title: docs
  - url: "http://pkg.julialang.org/"
    title: packages
  - url: "/blog/"
    title: blog
  - url: "/community/"
    title: community
  - url: "/learning/"
    title: learning
  - url: "/teaching/"
    title: teaching
  - url: "/publications/"
    title: publications
  - url: "/soc/"
    title: GSoC
  - url: "http://juliacon.org"
    title: juliacon
